
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JENKINS_PLUGINS="git pipeline-groovy-lib scm-api artifact-manager-s3 docker-workflow"
    restart: always

volumes:
  jenkins_home:

